# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbaack',
            old_name='contact_email',
            new_name='contactEmail',
        ),
        migrations.RenameField(
            model_name='feedbaack',
            old_name='content',
            new_name='contactMessage',
        ),
        migrations.RenameField(
            model_name='feedbaack',
            old_name='contact_name',
            new_name='contactName',
        ),
        migrations.AddField(
            model_name='feedbaack',
            name='contactSubject',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
